// Code generated by protoc-gen-go. DO NOT EDIT.
// source: agent.proto

package types

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AgentAuthReq_Action int32

const (
	AgentAuthReq_CONNECT AgentAuthReq_Action = 0
	AgentAuthReq_EXECUTE AgentAuthReq_Action = 1
	AgentAuthReq_PROXY   AgentAuthReq_Action = 2
	AgentAuthReq_FORWARD AgentAuthReq_Action = 3
)

var AgentAuthReq_Action_name = map[int32]string{
	0: "CONNECT",
	1: "EXECUTE",
	2: "PROXY",
	3: "FORWARD",
}

var AgentAuthReq_Action_value = map[string]int32{
	"CONNECT": 0,
	"EXECUTE": 1,
	"PROXY":   2,
	"FORWARD": 3,
}

func (x AgentAuthReq_Action) String() string {
	return proto.EnumName(AgentAuthReq_Action_name, int32(x))
}

func (AgentAuthReq_Action) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{2, 0}
}

type AgentRecordReq_Type int32

const (
	AgentRecordReq_STDOUT  AgentRecordReq_Type = 0
	AgentRecordReq_STDERR  AgentRecordReq_Type = 1
	AgentRecordReq_WINSIZE AgentRecordReq_Type = 2
)

var AgentRecordReq_Type_name = map[int32]string{
	0: "STDOUT",
	1: "STDERR",
	2: "WINSIZE",
}

var AgentRecordReq_Type_value = map[string]int32{
	"STDOUT":  0,
	"STDERR":  1,
	"WINSIZE": 2,
}

func (x AgentRecordReq_Type) String() string {
	return proto.EnumName(AgentRecordReq_Type_name, int32(x))
}

func (AgentRecordReq_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{4, 0}
}

type AgentPingReq struct {
	AgentId              string   `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Hostname             string   `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Port                 uint32   `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AgentPingReq) Reset()         { *m = AgentPingReq{} }
func (m *AgentPingReq) String() string { return proto.CompactTextString(m) }
func (*AgentPingReq) ProtoMessage()    {}
func (*AgentPingReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{0}
}

func (m *AgentPingReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgentPingReq.Unmarshal(m, b)
}
func (m *AgentPingReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgentPingReq.Marshal(b, m, deterministic)
}
func (m *AgentPingReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgentPingReq.Merge(m, src)
}
func (m *AgentPingReq) XXX_Size() int {
	return xxx_messageInfo_AgentPingReq.Size(m)
}
func (m *AgentPingReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AgentPingReq.DiscardUnknown(m)
}

var xxx_messageInfo_AgentPingReq proto.InternalMessageInfo

func (m *AgentPingReq) GetAgentId() string {
	if m != nil {
		return m.AgentId
	}
	return ""
}

func (m *AgentPingReq) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *AgentPingReq) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

type AgentPingResp struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AgentPingResp) Reset()         { *m = AgentPingResp{} }
func (m *AgentPingResp) String() string { return proto.CompactTextString(m) }
func (*AgentPingResp) ProtoMessage()    {}
func (*AgentPingResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{1}
}

func (m *AgentPingResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgentPingResp.Unmarshal(m, b)
}
func (m *AgentPingResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgentPingResp.Marshal(b, m, deterministic)
}
func (m *AgentPingResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgentPingResp.Merge(m, src)
}
func (m *AgentPingResp) XXX_Size() int {
	return xxx_messageInfo_AgentPingResp.Size(m)
}
func (m *AgentPingResp) XXX_DiscardUnknown() {
	xxx_messageInfo_AgentPingResp.DiscardUnknown(m)
}

var xxx_messageInfo_AgentPingResp proto.InternalMessageInfo

func (m *AgentPingResp) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *AgentPingResp) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type AgentAuthReq struct {
	Fingerprint string              `protobuf:"bytes,1,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	User        string              `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Hostname    string              `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Action      AgentAuthReq_Action `protobuf:"varint,4,opt,name=action,proto3,enum=antssh.AgentAuthReq_Action" json:"action,omitempty"`
	// Types that are valid to be assigned to Payload:
	//	*AgentAuthReq_Command
	//	*AgentAuthReq_Address
	Payload              isAgentAuthReq_Payload `protobuf_oneof:"payload"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *AgentAuthReq) Reset()         { *m = AgentAuthReq{} }
func (m *AgentAuthReq) String() string { return proto.CompactTextString(m) }
func (*AgentAuthReq) ProtoMessage()    {}
func (*AgentAuthReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{2}
}

func (m *AgentAuthReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgentAuthReq.Unmarshal(m, b)
}
func (m *AgentAuthReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgentAuthReq.Marshal(b, m, deterministic)
}
func (m *AgentAuthReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgentAuthReq.Merge(m, src)
}
func (m *AgentAuthReq) XXX_Size() int {
	return xxx_messageInfo_AgentAuthReq.Size(m)
}
func (m *AgentAuthReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AgentAuthReq.DiscardUnknown(m)
}

var xxx_messageInfo_AgentAuthReq proto.InternalMessageInfo

func (m *AgentAuthReq) GetFingerprint() string {
	if m != nil {
		return m.Fingerprint
	}
	return ""
}

func (m *AgentAuthReq) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *AgentAuthReq) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *AgentAuthReq) GetAction() AgentAuthReq_Action {
	if m != nil {
		return m.Action
	}
	return AgentAuthReq_CONNECT
}

type isAgentAuthReq_Payload interface {
	isAgentAuthReq_Payload()
}

type AgentAuthReq_Command struct {
	Command string `protobuf:"bytes,5,opt,name=command,proto3,oneof"`
}

type AgentAuthReq_Address struct {
	Address string `protobuf:"bytes,6,opt,name=address,proto3,oneof"`
}

func (*AgentAuthReq_Command) isAgentAuthReq_Payload() {}

func (*AgentAuthReq_Address) isAgentAuthReq_Payload() {}

func (m *AgentAuthReq) GetPayload() isAgentAuthReq_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *AgentAuthReq) GetCommand() string {
	if x, ok := m.GetPayload().(*AgentAuthReq_Command); ok {
		return x.Command
	}
	return ""
}

func (m *AgentAuthReq) GetAddress() string {
	if x, ok := m.GetPayload().(*AgentAuthReq_Address); ok {
		return x.Address
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*AgentAuthReq) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*AgentAuthReq_Command)(nil),
		(*AgentAuthReq_Address)(nil),
	}
}

type AgentAuthResp struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	RecordId             string   `protobuf:"bytes,3,opt,name=record_id,json=recordId,proto3" json:"record_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AgentAuthResp) Reset()         { *m = AgentAuthResp{} }
func (m *AgentAuthResp) String() string { return proto.CompactTextString(m) }
func (*AgentAuthResp) ProtoMessage()    {}
func (*AgentAuthResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{3}
}

func (m *AgentAuthResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgentAuthResp.Unmarshal(m, b)
}
func (m *AgentAuthResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgentAuthResp.Marshal(b, m, deterministic)
}
func (m *AgentAuthResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgentAuthResp.Merge(m, src)
}
func (m *AgentAuthResp) XXX_Size() int {
	return xxx_messageInfo_AgentAuthResp.Size(m)
}
func (m *AgentAuthResp) XXX_DiscardUnknown() {
	xxx_messageInfo_AgentAuthResp.DiscardUnknown(m)
}

var xxx_messageInfo_AgentAuthResp proto.InternalMessageInfo

func (m *AgentAuthResp) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *AgentAuthResp) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *AgentAuthResp) GetRecordId() string {
	if m != nil {
		return m.RecordId
	}
	return ""
}

type AgentRecordReq struct {
	RecordId  string              `protobuf:"bytes,1,opt,name=record_id,json=recordId,proto3" json:"record_id,omitempty"`
	Timestamp uint64              `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Type      AgentRecordReq_Type `protobuf:"varint,3,opt,name=type,proto3,enum=antssh.AgentRecordReq_Type" json:"type,omitempty"`
	// Types that are valid to be assigned to Payload:
	//	*AgentRecordReq_Data
	//	*AgentRecordReq_Size
	Payload              isAgentRecordReq_Payload `protobuf_oneof:"payload"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *AgentRecordReq) Reset()         { *m = AgentRecordReq{} }
func (m *AgentRecordReq) String() string { return proto.CompactTextString(m) }
func (*AgentRecordReq) ProtoMessage()    {}
func (*AgentRecordReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{4}
}

func (m *AgentRecordReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgentRecordReq.Unmarshal(m, b)
}
func (m *AgentRecordReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgentRecordReq.Marshal(b, m, deterministic)
}
func (m *AgentRecordReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgentRecordReq.Merge(m, src)
}
func (m *AgentRecordReq) XXX_Size() int {
	return xxx_messageInfo_AgentRecordReq.Size(m)
}
func (m *AgentRecordReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AgentRecordReq.DiscardUnknown(m)
}

var xxx_messageInfo_AgentRecordReq proto.InternalMessageInfo

func (m *AgentRecordReq) GetRecordId() string {
	if m != nil {
		return m.RecordId
	}
	return ""
}

func (m *AgentRecordReq) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *AgentRecordReq) GetType() AgentRecordReq_Type {
	if m != nil {
		return m.Type
	}
	return AgentRecordReq_STDOUT
}

type isAgentRecordReq_Payload interface {
	isAgentRecordReq_Payload()
}

type AgentRecordReq_Data struct {
	Data []byte `protobuf:"bytes,4,opt,name=data,proto3,oneof"`
}

type AgentRecordReq_Size struct {
	Size *AgentRecordReq_WinSize `protobuf:"bytes,5,opt,name=size,proto3,oneof"`
}

func (*AgentRecordReq_Data) isAgentRecordReq_Payload() {}

func (*AgentRecordReq_Size) isAgentRecordReq_Payload() {}

func (m *AgentRecordReq) GetPayload() isAgentRecordReq_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *AgentRecordReq) GetData() []byte {
	if x, ok := m.GetPayload().(*AgentRecordReq_Data); ok {
		return x.Data
	}
	return nil
}

func (m *AgentRecordReq) GetSize() *AgentRecordReq_WinSize {
	if x, ok := m.GetPayload().(*AgentRecordReq_Size); ok {
		return x.Size
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*AgentRecordReq) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*AgentRecordReq_Data)(nil),
		(*AgentRecordReq_Size)(nil),
	}
}

type AgentRecordReq_WinSize struct {
	Width                int32    `protobuf:"varint,1,opt,name=width,proto3" json:"width,omitempty"`
	Height               int32    `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AgentRecordReq_WinSize) Reset()         { *m = AgentRecordReq_WinSize{} }
func (m *AgentRecordReq_WinSize) String() string { return proto.CompactTextString(m) }
func (*AgentRecordReq_WinSize) ProtoMessage()    {}
func (*AgentRecordReq_WinSize) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{4, 0}
}

func (m *AgentRecordReq_WinSize) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgentRecordReq_WinSize.Unmarshal(m, b)
}
func (m *AgentRecordReq_WinSize) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgentRecordReq_WinSize.Marshal(b, m, deterministic)
}
func (m *AgentRecordReq_WinSize) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgentRecordReq_WinSize.Merge(m, src)
}
func (m *AgentRecordReq_WinSize) XXX_Size() int {
	return xxx_messageInfo_AgentRecordReq_WinSize.Size(m)
}
func (m *AgentRecordReq_WinSize) XXX_DiscardUnknown() {
	xxx_messageInfo_AgentRecordReq_WinSize.DiscardUnknown(m)
}

var xxx_messageInfo_AgentRecordReq_WinSize proto.InternalMessageInfo

func (m *AgentRecordReq_WinSize) GetWidth() int32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *AgentRecordReq_WinSize) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

type AgentRecordResp struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AgentRecordResp) Reset()         { *m = AgentRecordResp{} }
func (m *AgentRecordResp) String() string { return proto.CompactTextString(m) }
func (*AgentRecordResp) ProtoMessage()    {}
func (*AgentRecordResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{5}
}

func (m *AgentRecordResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgentRecordResp.Unmarshal(m, b)
}
func (m *AgentRecordResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgentRecordResp.Marshal(b, m, deterministic)
}
func (m *AgentRecordResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgentRecordResp.Merge(m, src)
}
func (m *AgentRecordResp) XXX_Size() int {
	return xxx_messageInfo_AgentRecordResp.Size(m)
}
func (m *AgentRecordResp) XXX_DiscardUnknown() {
	xxx_messageInfo_AgentRecordResp.DiscardUnknown(m)
}

var xxx_messageInfo_AgentRecordResp proto.InternalMessageInfo

func (m *AgentRecordResp) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *AgentRecordResp) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterEnum("antssh.AgentAuthReq_Action", AgentAuthReq_Action_name, AgentAuthReq_Action_value)
	proto.RegisterEnum("antssh.AgentRecordReq_Type", AgentRecordReq_Type_name, AgentRecordReq_Type_value)
	proto.RegisterType((*AgentPingReq)(nil), "antssh.AgentPingReq")
	proto.RegisterType((*AgentPingResp)(nil), "antssh.AgentPingResp")
	proto.RegisterType((*AgentAuthReq)(nil), "antssh.AgentAuthReq")
	proto.RegisterType((*AgentAuthResp)(nil), "antssh.AgentAuthResp")
	proto.RegisterType((*AgentRecordReq)(nil), "antssh.AgentRecordReq")
	proto.RegisterType((*AgentRecordReq_WinSize)(nil), "antssh.AgentRecordReq.WinSize")
	proto.RegisterType((*AgentRecordResp)(nil), "antssh.AgentRecordResp")
}

func init() { proto.RegisterFile("agent.proto", fileDescriptor_56ede974c0020f77) }

var fileDescriptor_56ede974c0020f77 = []byte{
	// 573 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0x5f, 0x6f, 0xda, 0x3e,
	0x14, 0x25, 0x34, 0x24, 0xcd, 0xa5, 0xed, 0x2f, 0xb2, 0xf8, 0x75, 0x19, 0x9d, 0x26, 0x94, 0x27,
	0xa4, 0x49, 0x99, 0x44, 0x37, 0x4d, 0xda, 0xb4, 0x07, 0x4a, 0x33, 0x95, 0x17, 0xa8, 0x0c, 0x15,
	0x6d, 0x5f, 0x36, 0x8f, 0x78, 0xc4, 0x12, 0xf9, 0xb3, 0xd8, 0x68, 0xa2, 0x9f, 0x63, 0x5f, 0x66,
	0x2f, 0xfb, 0x6c, 0x93, 0x1d, 0xa7, 0x03, 0xc4, 0x5e, 0xfa, 0xe6, 0x73, 0x7c, 0xef, 0xf1, 0xf1,
	0xb9, 0x4e, 0xa0, 0x49, 0x16, 0x34, 0x15, 0x41, 0x5e, 0x64, 0x22, 0x43, 0x16, 0x49, 0x05, 0xe7,
	0xb1, 0x7f, 0x07, 0x47, 0x7d, 0x49, 0x5f, 0xb3, 0x74, 0x81, 0xe9, 0x77, 0xf4, 0x1c, 0x0e, 0x55,
	0xd9, 0x67, 0x16, 0x79, 0x46, 0xc7, 0xe8, 0x3a, 0xd8, 0x56, 0x78, 0x18, 0xa1, 0x36, 0x1c, 0xc6,
	0x19, 0x17, 0x29, 0x49, 0xa8, 0x57, 0x57, 0x5b, 0x8f, 0x18, 0x21, 0x30, 0xf3, 0xac, 0x10, 0xde,
	0x41, 0xc7, 0xe8, 0x1e, 0x63, 0xb5, 0xf6, 0x07, 0x70, 0xbc, 0x21, 0xcd, 0x73, 0xe4, 0x81, 0xcd,
	0x57, 0xf3, 0x39, 0xe5, 0x5c, 0x49, 0x1f, 0xe2, 0x0a, 0xca, 0x9d, 0x84, 0x72, 0x4e, 0x16, 0x95,
	0x72, 0x05, 0xfd, 0x9f, 0x75, 0x6d, 0xb0, 0xbf, 0x12, 0xb1, 0x34, 0xd8, 0x81, 0xe6, 0x37, 0x96,
	0x2e, 0x68, 0x91, 0x17, 0x2c, 0x15, 0xda, 0xe3, 0x26, 0x25, 0xbd, 0xac, 0x38, 0x2d, 0xb4, 0x92,
	0x5a, 0x6f, 0x79, 0x3f, 0xd8, 0xf1, 0x7e, 0x0e, 0x16, 0x99, 0x0b, 0x96, 0xa5, 0x9e, 0xd9, 0x31,
	0xba, 0x27, 0xbd, 0xb3, 0xa0, 0xcc, 0x26, 0xd8, 0x3c, 0x37, 0xe8, 0xab, 0x12, 0xac, 0x4b, 0x51,
	0x1b, 0xec, 0x79, 0x96, 0x24, 0x24, 0x8d, 0xbc, 0x86, 0xd4, 0xbb, 0xaa, 0xe1, 0x8a, 0x90, 0x7b,
	0x24, 0x8a, 0x0a, 0x79, 0x4f, 0xab, 0xda, 0xd3, 0x84, 0xff, 0x1e, 0xac, 0x52, 0x09, 0x35, 0xc1,
	0x1e, 0x8c, 0x47, 0xa3, 0x70, 0x30, 0x75, 0x6b, 0x12, 0x84, 0xb7, 0xe1, 0xe0, 0x66, 0x1a, 0xba,
	0x06, 0x72, 0xa0, 0x71, 0x8d, 0xc7, 0xb7, 0x77, 0x6e, 0x5d, 0xf2, 0x9f, 0xc6, 0x78, 0xd6, 0xc7,
	0x97, 0xee, 0xc1, 0x85, 0x03, 0x76, 0x4e, 0xd6, 0xcb, 0x8c, 0x44, 0xfe, 0x17, 0x9d, 0x6d, 0xe9,
	0xee, 0x69, 0xd9, 0xa2, 0x33, 0x70, 0x0a, 0x3a, 0xcf, 0x8a, 0x48, 0x0e, 0x5b, 0xa7, 0x52, 0x12,
	0xc3, 0xc8, 0xff, 0x55, 0x87, 0x13, 0x75, 0x04, 0x56, 0x8c, 0x8c, 0x7e, 0xab, 0xde, 0xd8, 0xae,
	0x47, 0x2f, 0xc0, 0x11, 0x2c, 0xa1, 0x5c, 0x90, 0x24, 0x57, 0x07, 0x99, 0xf8, 0x2f, 0x81, 0x5e,
	0x83, 0x29, 0xd6, 0x79, 0x99, 0xfd, 0x6e, 0xc2, 0x8f, 0x07, 0x04, 0xd3, 0x75, 0x4e, 0xb1, 0x2a,
	0x44, 0x2d, 0x30, 0x23, 0x22, 0x88, 0x1a, 0xc9, 0xd1, 0x55, 0x0d, 0x2b, 0x84, 0xde, 0x80, 0xc9,
	0xd9, 0x03, 0x55, 0x91, 0x37, 0x7b, 0x2f, 0xff, 0x21, 0x33, 0x63, 0xe9, 0x84, 0x3d, 0x50, 0xd9,
	0x25, 0xab, 0xdb, 0xef, 0xc0, 0xd6, 0x14, 0x6a, 0x41, 0xe3, 0x07, 0x8b, 0x44, 0xac, 0xec, 0x37,
	0x70, 0x09, 0xd0, 0x29, 0x58, 0x31, 0x65, 0x8b, 0x58, 0x28, 0xe3, 0x0d, 0xac, 0x91, 0xff, 0x0a,
	0x4c, 0x69, 0x09, 0x01, 0x58, 0x93, 0xe9, 0xe5, 0xf8, 0x46, 0x4e, 0xaa, 0x5c, 0x87, 0x18, 0xbb,
	0x86, 0x9c, 0xce, 0x6c, 0x38, 0x9a, 0x0c, 0xef, 0x43, 0xb7, 0xbe, 0x39, 0x9d, 0x10, 0xfe, 0xdb,
	0xb2, 0xf4, 0xb4, 0xf9, 0xf4, 0x7e, 0x1b, 0x5a, 0x67, 0x90, 0xa5, 0xa2, 0xc8, 0x96, 0x4b, 0x5a,
	0xa0, 0xb7, 0x60, 0xca, 0xef, 0x09, 0xb5, 0xb6, 0xee, 0xae, 0xbf, 0xde, 0xf6, 0xff, 0x7b, 0x58,
	0x9e, 0xfb, 0x35, 0xd9, 0x26, 0x9f, 0xca, 0x4e, 0x9b, 0x7e, 0xdb, 0x3b, 0x6d, 0xd5, 0x9b, 0xf2,
	0x6b, 0xe8, 0x23, 0x58, 0xe5, 0x1d, 0xd0, 0xe9, 0xfe, 0xac, 0xdb, 0xcf, 0xf6, 0xf2, 0xb2, 0xb9,
	0x6b, 0x5c, 0x38, 0xf7, 0x76, 0xf0, 0x41, 0x8e, 0x93, 0x7f, 0xb5, 0xd4, 0x6f, 0xe7, 0xfc, 0x4f,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x81, 0xbe, 0xe1, 0x9b, 0x85, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AgentControllerClient is the client API for AgentController service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AgentControllerClient interface {
	Ping(ctx context.Context, in *AgentPingReq, opts ...grpc.CallOption) (*AgentPingResp, error)
	Auth(ctx context.Context, in *AgentAuthReq, opts ...grpc.CallOption) (*AgentAuthResp, error)
	Record(ctx context.Context, opts ...grpc.CallOption) (AgentController_RecordClient, error)
}

type agentControllerClient struct {
	cc *grpc.ClientConn
}

func NewAgentControllerClient(cc *grpc.ClientConn) AgentControllerClient {
	return &agentControllerClient{cc}
}

func (c *agentControllerClient) Ping(ctx context.Context, in *AgentPingReq, opts ...grpc.CallOption) (*AgentPingResp, error) {
	out := new(AgentPingResp)
	err := c.cc.Invoke(ctx, "/antssh.AgentController/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentControllerClient) Auth(ctx context.Context, in *AgentAuthReq, opts ...grpc.CallOption) (*AgentAuthResp, error) {
	out := new(AgentAuthResp)
	err := c.cc.Invoke(ctx, "/antssh.AgentController/Auth", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentControllerClient) Record(ctx context.Context, opts ...grpc.CallOption) (AgentController_RecordClient, error) {
	stream, err := c.cc.NewStream(ctx, &_AgentController_serviceDesc.Streams[0], "/antssh.AgentController/Record", opts...)
	if err != nil {
		return nil, err
	}
	x := &agentControllerRecordClient{stream}
	return x, nil
}

type AgentController_RecordClient interface {
	Send(*AgentRecordReq) error
	CloseAndRecv() (*AgentRecordResp, error)
	grpc.ClientStream
}

type agentControllerRecordClient struct {
	grpc.ClientStream
}

func (x *agentControllerRecordClient) Send(m *AgentRecordReq) error {
	return x.ClientStream.SendMsg(m)
}

func (x *agentControllerRecordClient) CloseAndRecv() (*AgentRecordResp, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(AgentRecordResp)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// AgentControllerServer is the server API for AgentController service.
type AgentControllerServer interface {
	Ping(context.Context, *AgentPingReq) (*AgentPingResp, error)
	Auth(context.Context, *AgentAuthReq) (*AgentAuthResp, error)
	Record(AgentController_RecordServer) error
}

// UnimplementedAgentControllerServer can be embedded to have forward compatible implementations.
type UnimplementedAgentControllerServer struct {
}

func (*UnimplementedAgentControllerServer) Ping(ctx context.Context, req *AgentPingReq) (*AgentPingResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (*UnimplementedAgentControllerServer) Auth(ctx context.Context, req *AgentAuthReq) (*AgentAuthResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Auth not implemented")
}
func (*UnimplementedAgentControllerServer) Record(srv AgentController_RecordServer) error {
	return status.Errorf(codes.Unimplemented, "method Record not implemented")
}

func RegisterAgentControllerServer(s *grpc.Server, srv AgentControllerServer) {
	s.RegisterService(&_AgentController_serviceDesc, srv)
}

func _AgentController_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentPingReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentControllerServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/antssh.AgentController/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentControllerServer).Ping(ctx, req.(*AgentPingReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentController_Auth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentAuthReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentControllerServer).Auth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/antssh.AgentController/Auth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentControllerServer).Auth(ctx, req.(*AgentAuthReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentController_Record_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentControllerServer).Record(&agentControllerRecordServer{stream})
}

type AgentController_RecordServer interface {
	SendAndClose(*AgentRecordResp) error
	Recv() (*AgentRecordReq, error)
	grpc.ServerStream
}

type agentControllerRecordServer struct {
	grpc.ServerStream
}

func (x *agentControllerRecordServer) SendAndClose(m *AgentRecordResp) error {
	return x.ServerStream.SendMsg(m)
}

func (x *agentControllerRecordServer) Recv() (*AgentRecordReq, error) {
	m := new(AgentRecordReq)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _AgentController_serviceDesc = grpc.ServiceDesc{
	ServiceName: "antssh.AgentController",
	HandlerType: (*AgentControllerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _AgentController_Ping_Handler,
		},
		{
			MethodName: "Auth",
			Handler:    _AgentController_Auth_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Record",
			Handler:       _AgentController_Record_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "agent.proto",
}
